// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package admin_events_repository

import (
	"time"

	"github.com/wesleyfebarretos/ticket-sale/repository/override"
)

type Event struct {
	ID        int32      `json:"id"`
	ProductID int32      `json:"productId"`
	StartAt   *time.Time `json:"startAt"`
	EndAt     *time.Time `json:"endAt"`
	City      *string    `json:"city"`
	State     *string    `json:"state"`
	Location  *string    `json:"location"`
}

type GetAllEvent struct {
	ID        int32                 `json:"id"`
	ProductID int32                 `json:"productId"`
	StartAt   *time.Time            `json:"startAt"`
	EndAt     *time.Time            `json:"endAt"`
	City      *string               `json:"city"`
	State     *string               `json:"state"`
	Location  *string               `json:"location"`
	Product   override.EventProduct `json:"product"`
}
