// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package gateway_customer_connection

import (
	"time"
)

type FinGatewayCustomer struct {
	UserID            int32     `json:"userId"`
	GatewayID         int32     `json:"gatewayId"`
	GatewayCustomerID string    `json:"gatewayCustomerId"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}
