version: '3.5'

services:
  postgres:
    container_name: ticket-sale
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ticket_sale
      PGDATA: /data/postgres
    volumes:
       - pgdata:/data/postgres
    ports:
      - "5432:5432"
    networks:
    - app
    restart: unless-stopped

volumes:
    pgdata:
      driver: local

networks:
  app:
    driver: bridge
