version: '3.5'

services:
  postgres:
    container_name: ticket-sale-db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ticket_sale
      PGDATA: /data/postgres
    volumes:
       - pgdata:/data/postgres
    ports:
      - "5432:5432"
    networks:
    - app
    restart: unless-stopped

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.14.2'
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=elastic
    ports:
      - "9200:9200"
    networks:
    - app
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  pgdata:
    driver: local
  esdata:
    driver: local

networks:
  app:
    driver: bridge
