// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Ticket Sale Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/users": {
            "get": {
                "description": "Get All Admin Users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Users"
                ],
                "summary": "Get All",
                "parameters": [
                    {
                        "type": "string",
                        "default": "token=xxx",
                        "description": "token",
                        "name": "Cookie",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/admin_user_controller.GetAllResponseDto"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.AuthenticationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/exception.HttpException"
                        }
                    }
                }
            }
        },
        "/auth": {
            "post": {
                "description": "Sign In with and User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Sign In",
                "parameters": [
                    {
                        "description": "Sign In",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/middleware.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.SignInResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.AuthenticationError"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Get All Users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get All",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user_controller.GetAllResponseDto"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/exception.HttpException"
                        }
                    }
                }
            },
            "post": {
                "description": "Create an new User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "Add user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_controller.CreateRequestDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/user_controller.CreateResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/exception.HttpException"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/exception.HttpException"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin_user_controller.GetAllResponseDto": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2024-06-29T06:29:44.999929Z"
                },
                "email": {
                    "type": "string",
                    "example": "johndoe@gmail.com"
                },
                "firstName": {
                    "type": "string",
                    "example": "John"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "role": {
                    "type": "string",
                    "example": "admin"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2024-06-29T06:29:44.999929Z"
                }
            }
        },
        "exception.HttpException": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid path parameter"
                },
                "statusCode": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "middleware.AuthenticationError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Access denied"
                },
                "statusCode": {
                    "type": "integer",
                    "example": 401
                }
            }
        },
        "middleware.SignInRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "johndoe@gmail.com"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "middleware.SignInResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "expire": {
                    "type": "string",
                    "example": "2024-06-30T20:46:13-03:00"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTk3OTExNzMsImlkIjozLCJvcmlnX2lhdCI6MTcxOTcwNDc3Mywicm9sZSI6InVzZXIifQ.c8HuyRAxgNDC4FavwQ_mv-qWOm4Ch6--1-kSQEmK4x0"
                }
            }
        },
        "user_controller.AddressRequestDto": {
            "type": "object",
            "properties": {
                "addressType": {
                    "type": "string",
                    "example": "home"
                },
                "city": {
                    "type": "string",
                    "example": "Springfield"
                },
                "complement": {
                    "type": "string",
                    "example": "Apt 101"
                },
                "country": {
                    "type": "string",
                    "example": "USA"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "favorite": {
                    "type": "boolean",
                    "example": true
                },
                "postalCode": {
                    "type": "string",
                    "example": "12345"
                },
                "state": {
                    "type": "string",
                    "example": "IL"
                },
                "streetAddress": {
                    "type": "string",
                    "example": "123 Main St"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2023-01-02T00:00:00Z"
                }
            }
        },
        "user_controller.AddressResponseDto": {
            "type": "object",
            "properties": {
                "addressType": {
                    "type": "string",
                    "example": "home"
                },
                "city": {
                    "type": "string",
                    "example": "Springfield"
                },
                "complement": {
                    "type": "string",
                    "example": "Apt 101"
                },
                "country": {
                    "type": "string",
                    "example": "USA"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "favorite": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "postalCode": {
                    "type": "string",
                    "example": "12345"
                },
                "state": {
                    "type": "string",
                    "example": "IL"
                },
                "streetAddress": {
                    "type": "string",
                    "example": "123 Main St"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2023-01-02T00:00:00Z"
                },
                "userId": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "user_controller.CreateRequestDto": {
            "type": "object",
            "required": [
                "email",
                "firstName",
                "lastName",
                "password"
            ],
            "properties": {
                "address": {
                    "$ref": "#/definitions/user_controller.AddressRequestDto"
                },
                "email": {
                    "type": "string",
                    "example": "johndoe@gmail.com"
                },
                "firstName": {
                    "type": "string",
                    "example": "John"
                },
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "user_controller.CreateResponseDto": {
            "type": "object",
            "required": [
                "email",
                "firstName",
                "lastName"
            ],
            "properties": {
                "address": {
                    "$ref": "#/definitions/user_controller.AddressResponseDto"
                },
                "email": {
                    "type": "string",
                    "example": "johndoe@gmail.com"
                },
                "firstName": {
                    "type": "string",
                    "example": "John"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "role": {
                    "type": "string",
                    "example": "user"
                }
            }
        },
        "user_controller.GetAllResponseDto": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "jwt_ticket_sale",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Ticket Sale",
	Description:      "This is a simple ticket selling application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
