// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users_phones_query.sql

package users_phones_repository

import (
	"context"
)

const create = `-- name: Create :one
INSERT INTO users_phones
    (user_id, ddd, number, type)
VALUES 
    ($1, $2, $3, $4) 
RETURNING id, user_id, ddd, number, type
`

type CreateParams struct {
	UserID int32      `json:"userId"`
	Ddd    string     `json:"ddd"`
	Number string     `json:"number"`
	Type   PhoneTypes `json:"type"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (UsersPhone, error) {
	row := q.db.QueryRow(ctx, create,
		arg.UserID,
		arg.Ddd,
		arg.Number,
		arg.Type,
	)
	var i UsersPhone
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Ddd,
		&i.Number,
		&i.Type,
	)
	return i, err
}
