version: '3.5'

services:
  postgres:
    container_name: ticket-sale
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ticket_sale
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
    - ticket-sale
    restart: unless-stopped

volumes:
    postgres:

networks:
  ticket-sale:
    driver: bridge
