// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package admin_products_repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/wesleyfebarretos/ticket-sale/repository/override"
)

type Product struct {
	ID             int32     `json:"id"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	Uuid           uuid.UUID `json:"uuid"`
	Price          float64   `json:"price"`
	DiscountPrice  *float64  `json:"discountPrice"`
	Active         bool      `json:"active"`
	IsDeleted      bool      `json:"isDeleted"`
	Image          *string   `json:"image"`
	ImageMobile    *string   `json:"imageMobile"`
	ImageThumbnail *string   `json:"imageThumbnail"`
	CategoryID     int32     `json:"categoryId"`
	CreatedBy      int32     `json:"createdBy"`
	UpdatedBy      *int32    `json:"updatedBy"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type ProductsWithRelation struct {
	ID             int32                    `json:"id"`
	Name           string                   `json:"name"`
	Description    *string                  `json:"description"`
	Uuid           uuid.UUID                `json:"uuid"`
	Price          float64                  `json:"price"`
	DiscountPrice  *float64                 `json:"discountPrice"`
	Active         bool                     `json:"active"`
	IsDeleted      bool                     `json:"isDeleted"`
	Image          *string                  `json:"image"`
	ImageMobile    *string                  `json:"imageMobile"`
	ImageThumbnail *string                  `json:"imageThumbnail"`
	CategoryID     int32                    `json:"categoryId"`
	CreatedBy      int32                    `json:"createdBy"`
	UpdatedBy      *int32                   `json:"updatedBy"`
	CreatedAt      time.Time                `json:"createdAt"`
	UpdatedAt      time.Time                `json:"updatedAt"`
	Stock          *override.ProductStock   `json:"stock"`
	Category       override.ProductCategory `json:"category"`
}
