// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package payment_order_connection

import (
	"time"

	"github.com/google/uuid"
)

type FinPaymentOrder struct {
	ID                    int32      `json:"id"`
	Uuid                  uuid.UUID  `json:"uuid"`
	CreditcardUuid        *uuid.UUID `json:"creditcardUuid"`
	UserID                int32      `json:"userId"`
	TotalPrice            float64    `json:"totalPrice"`
	PaymentTypeID         int32      `json:"paymentTypeId"`
	InstallmentTimeID     int32      `json:"installmentTimeId"`
	GatewayID             int32      `json:"gatewayId"`
	PaymentStatusID       int32      `json:"paymentStatusId"`
	PaymentCancelReasonID *int32     `json:"paymentCancelReasonId"`
	ExtraInfo             *string    `json:"extraInfo"`
	PaymentAt             *time.Time `json:"paymentAt"`
	CancelAt              *time.Time `json:"cancelAt"`
	DueAt                 *time.Time `json:"dueAt"`
	ExpirationAt          *time.Time `json:"expirationAt"`
	BaseValue             float64    `json:"baseValue"`
	ReversedValue         float64    `json:"reversedValue"`
	CanceledValue         float64    `json:"canceledValue"`
	AddedValue            float64    `json:"addedValue"`
	TotalValue            float64    `json:"totalValue"`
	CreatedBy             int32      `json:"createdBy"`
	UpdatedBy             *int32     `json:"updatedBy"`
	CreatedAt             time.Time  `json:"createdAt"`
	UpdatedAt             time.Time  `json:"updatedAt"`
}
