// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package gateway_customer_card_connection

import (
	"time"
)

type FinGatewayCustomerCard struct {
	ID            int32     `json:"id"`
	GatewayID     int32     `json:"gatewayId"`
	UserID        int32     `json:"userId"`
	CardID        int32     `json:"cardId"`
	GatewayCardID string    `json:"gatewayCardId"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}
