// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin_gateway_provider_query.sql

package admin_gateway_provider_connection

import (
	"context"
)

const create = `-- name: Create :one
INSERT INTO fin.gateway_provider
    (name, created_by, updated_by)
VALUES
    ($1,$2,$3)
RETURNING id, name, created_by, updated_by, created_at, updated_at
`

type CreateParams struct {
	Name      string `json:"name"`
	CreatedBy int32  `json:"createdBy"`
	UpdatedBy int32  `json:"updatedBy"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (FinGatewayProvider, error) {
	row := q.db.QueryRow(ctx, create, arg.Name, arg.CreatedBy, arg.UpdatedBy)
	var i FinGatewayProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
