// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package admin_gateway_provider_connection

import (
	"time"
)

type FinGatewayProvider struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedBy int32     `json:"createdBy"`
	UpdatedBy int32     `json:"updatedBy"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
