// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package admin_product_connection

import (
	"time"

	"github.com/google/uuid"
	"github.com/wesleyfebarretos/ticket-sale/internal/api/domain/repository/override"
)

type FinProductPaymentTypeInstallmentTime struct {
	ID                int32     `json:"id"`
	ProductID         int32     `json:"productId"`
	PaymentTypeID     int32     `json:"paymentTypeId"`
	InstallmentTimeID int32     `json:"installmentTimeId"`
	Fee               float64   `json:"fee"`
	Tariff            float64   `json:"tariff"`
	CreatedBy         int32     `json:"createdBy"`
	UpdatedBy         *int32    `json:"updatedBy"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

type Product struct {
	ID             int32     `json:"id"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	Uuid           uuid.UUID `json:"uuid"`
	Price          float64   `json:"price"`
	DiscountPrice  *float64  `json:"discountPrice"`
	Active         bool      `json:"active"`
	IsDeleted      bool      `json:"isDeleted"`
	Image          *string   `json:"image"`
	ImageMobile    *string   `json:"imageMobile"`
	ImageThumbnail *string   `json:"imageThumbnail"`
	CategoryID     int32     `json:"categoryId"`
	CreatedBy      int32     `json:"createdBy"`
	UpdatedBy      *int32    `json:"updatedBy"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type ProductsDetail struct {
	ID             int32                        `json:"id"`
	Name           string                       `json:"name"`
	Description    *string                      `json:"description"`
	Uuid           uuid.UUID                    `json:"uuid"`
	Price          float64                      `json:"price"`
	DiscountPrice  *float64                     `json:"discountPrice"`
	Active         bool                         `json:"active"`
	IsDeleted      bool                         `json:"isDeleted"`
	Image          *string                      `json:"image"`
	ImageMobile    *string                      `json:"imageMobile"`
	ImageThumbnail *string                      `json:"imageThumbnail"`
	CategoryID     int32                        `json:"categoryId"`
	CreatedBy      int32                        `json:"createdBy"`
	UpdatedBy      *int32                       `json:"updatedBy"`
	CreatedAt      time.Time                    `json:"createdAt"`
	UpdatedAt      time.Time                    `json:"updatedAt"`
	Stock          *override.ProductStock       `json:"stock"`
	Category       override.ProductCategory     `json:"category"`
	Installments   override.ProductInstallments `json:"installments"`
}
