// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package creditcard_connection

import (
	"time"

	"github.com/google/uuid"
	"github.com/wesleyfebarretos/ticket-sale/internal/api/domain/repository/override"
)

type FinCreditcard struct {
	ID               int32     `json:"id"`
	Uuid             uuid.UUID `json:"uuid"`
	Name             string    `json:"name"`
	Number           string    `json:"number"`
	Expiration       time.Time `json:"expiration"`
	Priority         int32     `json:"priority"`
	NotifyExpiration bool      `json:"notifyExpiration"`
	UserID           int32     `json:"userId"`
	CreditcardTypeID int32     `json:"creditcardTypeId"`
	CreditcardFlagID int32     `json:"creditcardFlagId"`
	IsDeleted        bool      `json:"isDeleted"`
	CreatedAt        time.Time `json:"createdAt"`
	UpdatedAt        time.Time `json:"updatedAt"`
}

type UserCreditcard struct {
	Uuid           uuid.UUID               `json:"uuid"`
	Name           string                  `json:"name"`
	Number         string                  `json:"number"`
	Expiration     time.Time               `json:"expiration"`
	UserID         int32                   `json:"userId"`
	CreatedAt      time.Time               `json:"createdAt"`
	CreditcardFlag override.CreditcardFlag `json:"creditcardFlag"`
	CreditcardType override.CreditcardType `json:"creditcardType"`
}
