// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package admin_gateway_repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/wesleyfebarretos/ticket-sale/internal/api/domain/repository/override"
)

type GatewayAuthType string

const (
	GatewayAuthTypeBearer GatewayAuthType = "bearer"
	GatewayAuthTypeBasic  GatewayAuthType = "basic"
)

func (e *GatewayAuthType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GatewayAuthType(s)
	case string:
		*e = GatewayAuthType(s)
	default:
		return fmt.Errorf("unsupported scan type for GatewayAuthType: %T", src)
	}
	return nil
}

type NullGatewayAuthType struct {
	GatewayAuthType GatewayAuthType `json:"gatewayAuthType"`
	Valid           bool            `json:"valid"` // Valid is true if GatewayAuthType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGatewayAuthType) Scan(value interface{}) error {
	if value == nil {
		ns.GatewayAuthType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GatewayAuthType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGatewayAuthType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GatewayAuthType), nil
}

func (e GatewayAuthType) Valid() bool {
	switch e {
	case GatewayAuthTypeBearer,
		GatewayAuthTypeBasic:
		return true
	}
	return false
}

func AllGatewayAuthTypeValues() []GatewayAuthType {
	return []GatewayAuthType{
		GatewayAuthTypeBearer,
		GatewayAuthTypeBasic,
	}
}

type FinGateway struct {
	ID               int32           `json:"id"`
	Uuid             uuid.UUID       `json:"uuid"`
	Name             string          `json:"name"`
	Description      *string         `json:"description"`
	ClientID         *string         `json:"clientId"`
	ClientSecret     *string         `json:"clientSecret"`
	Order            int32           `json:"order"`
	Active           bool            `json:"active"`
	IsDeleted        bool            `json:"isDeleted"`
	TestEnvironment  bool            `json:"testEnvironment"`
	NotifUser        *string         `json:"notifUser"`
	NotifPassword    *string         `json:"notifPassword"`
	SoftDescriptor   *string         `json:"softDescriptor"`
	GatewayProcessID int32           `json:"gatewayProcessId"`
	WebhookUrl       *string         `json:"webhookUrl"`
	Url              *string         `json:"url"`
	AuthType         GatewayAuthType `json:"authType"`
	Use3ds           bool            `json:"use3ds"`
	AdqCode3ds       *string         `json:"adqCode3ds"`
	DefaultAdqCode   *string         `json:"defaultAdqCode"`
	UseAntifraud     bool            `json:"useAntifraud"`
	CreatedBy        int32           `json:"createdBy"`
	UpdatedBy        *int32          `json:"updatedBy"`
	CreatedAt        time.Time       `json:"createdAt"`
	UpdatedAt        time.Time       `json:"updatedAt"`
}

type GatewayDetail struct {
	ID                  int32                          `json:"id"`
	Uuid                uuid.UUID                      `json:"uuid"`
	Name                string                         `json:"name"`
	Description         *string                        `json:"description"`
	ClientID            *string                        `json:"clientId"`
	ClientSecret        *string                        `json:"clientSecret"`
	Order               int32                          `json:"order"`
	Active              bool                           `json:"active"`
	TestEnvironment     bool                           `json:"testEnvironment"`
	NotifUser           *string                        `json:"notifUser"`
	NotifPassword       *string                        `json:"notifPassword"`
	SoftDescriptor      *string                        `json:"softDescriptor"`
	GatewayProcessID    int32                          `json:"gatewayProcessId"`
	WebhookUrl          *string                        `json:"webhookUrl"`
	Url                 *string                        `json:"url"`
	AuthType            GatewayAuthType                `json:"authType"`
	Use3ds              bool                           `json:"use3ds"`
	AdqCode3ds          *string                        `json:"adqCode3ds"`
	DefaultAdqCode      *string                        `json:"defaultAdqCode"`
	UseAntifraud        bool                           `json:"useAntifraud"`
	CreatedBy           int32                          `json:"createdBy"`
	UpdatedBy           *int32                         `json:"updatedBy"`
	CreatedAt           time.Time                      `json:"createdAt"`
	UpdatedAt           time.Time                      `json:"updatedAt"`
	GatewayProcess      override.GatewayProcess        `json:"gatewayProcess"`
	GatewayPaymentTypes []override.GatewayPaymentTypes `json:"gatewayPaymentTypes"`
}
